version: "3"
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test # ${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=test # ${MONGO_PASSWORD}
      # MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - '27017:27017'